config/routes.rb
Rails.application.routes.draw do

  resources :journeys, only: [:index,:new,:show, :create]
  resources :negotiators
  root 'journeys#new'

end

app/models/city_mapper_request.rb
class CityMapperRequest

  REQUEST_DOMAIN = 'developer.citymapper.com'
  API_RESOURCE = 'api/1/traveltime'
  def initialize(start: nil,finish: nil,time: nil)
    @start = start
    @finish = finish
    @time = time
  end

  def uri
    params = {
               "key" => api_key,
               "time_type" => 'arrival',
               "time" => @time,
               "startcoord" => @start.to_s,
               "endcoord" => @finish.to_s
             }
    uri_str = "https://#{REQUEST_DOMAIN}/#{API_RESOURCE}/?#{params.to_param}"
    URI.parse(uri_str)
  end

  def api_key
    ENV['CITYMAPPER_API_KEY']
  end

end

app/models/journey.rb
class Journey < ActiveRecord::Base
  has_many :visits, dependent: :destroy
  belongs_to :negotiator
  validates :negotiator, presence: true
  validates :starts, presence: true
  validates :visits , presence: true

  before_validation :set_start_point

  attr_accessor :locations

  def build_visits
    location_set = JSON.parse(self.locations)
    visit = self.visits.last
    self.transaction do
      location_set.each do |l|
        lat = Float(l["lat"]).round(6)
        lng = Float(l["lng"]).round(6)
        location = Location.find_or_create_by( latitude: lat,
                                               longitude: lng )
        if location.id == nil
          raise "Location #{l} failed #{location}.errors"
        end
        visit = visit.build_visit_to(location: location)
      end
    end
    self.visits
  end

  private

  def set_start_point
    if visits.blank?
      visits << Visit.new( location: Location.london_office,
                           arrival: Time.now)
    end
  end




end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :latitude, presence: true
  validates :longitude, presence: true,
            uniqueness: { scope: :latitude  }
  has_many :visits


  BASE_LOCATION = { latitude: 51.51991, longitude: -0.09820 }

  def self.london_office
    location = Location.find_or_create_by( latitude: BASE_LOCATION[:latitude],
                                           longitude: BASE_LOCATION[:longitude])
  end

  def to_s
    "#{latitude},#{longitude}"
  end


end

app/models/negotiator.rb
class Negotiator < ActiveRecord::Base
  validates :username, presence: true
  has_many :journeys
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  validates :journey, presence: true
  belongs_to :location
  belongs_to :journey

  before_save :ensure_duration_is_set

  def build_visit_to (location: nil )
    time = journey_time(to:location)
    if time > 0
      time = self.leaves_at + time
    end
    Visit.create!( location: location, journey: self.journey,
                   arrival: time)
  end

  def leaves_at
    if not arrival.blank?
      self.arrival + self.duration_seconds
    end
  end

  def journey_time (to: loc)
    response = city_mapper_lookup( from: self.location, to: to,
                                   time: self.leaves_at )
    minutes = response["travel_time_minutes"]
    minutes * 60
  end

  private

  def city_mapper_lookup( from: loc, to: loc, time: nil )
    # rate limit to 50 reqs per day for free acct. !!
    #    request = CityMapperRequest.new(start: from, finish: to, time: time)
    #    response = Net::HTTP.get_response(request.uri)
    fake_cm_response= %Q|{
      "travel_time_minutes": #{rand(30)},
          "diagnostic": {
                          "milliseconds": 3502
                        }
    }|
    JSON.parse(fake_cm_response)
  end

  def ensure_duration_is_set
    if self.duration_seconds.blank?
      self.duration_seconds = 15 * 60
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def needs_negotiators?
    (Negotiator.count < 1)
  end


end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :set_journey, only: [:show, :edit, :update, :destroy]

  # GET /journeys
  def index
    @journeys = Journey.all
  end

  # GET /journeys/1
  def show
  end

  # GET /journeys/new
  def new
    if needs_negotiators?
      redirect_to new_negotiator_url, notice: 'The system needs at least one negotiator to plan journeys'
    else
      @journey = Journey.new
    end
  end

  # GET /journeys/1/edit
  def edit
  end


  # POST /journeys
  def create
    negotiator = Negotiator.find_by_id(journey_params[:negotiator_id])

    @journey = Journey.new(negotiator: negotiator, starts: journey_params[:starts])
    @journey.locations = journey_params[:locations]
    if @journey.save and @journey.build_visits
      redirect_to @journey, notice: 'Journey was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /journeys/1
  def update
    if @journey.update(journey_params)
      redirect_to @journey, notice: 'Journey was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /journeys/1
  def destroy
    @journey.destroy
    redirect_to journeys_url, notice: 'Journey was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journey
      @journey = Journey.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def journey_params
      params.require(:journey).permit(:locations,:starts,:negotiator_id)
    end
end

app/controllers/negotiators_controller.rb
class NegotiatorsController < ApplicationController
  before_action :set_negotiator, only: [:show, :edit, :update, :destroy]

  # GET /negotiators
  def index
    @negotiators = Negotiator.all
  end

  # GET /negotiators/1
  def show
  end

  # GET /negotiators/new
  def new
    @negotiator = Negotiator.new
  end

  # GET /negotiators/1/edit
  def edit
  end

  # POST /negotiators
  def create
    @negotiator = Negotiator.new(negotiator_params)

    if @negotiator.save
      redirect_to @negotiator, notice: 'Negotiator was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /negotiators/1
  def update

    if negotiator_params.any? and @negotiator.update(negotiator_params)
      redirect_to @negotiator, notice: 'Negotiator was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /negotiators/1
  def destroy
    @negotiator.destroy
    redirect_to negotiators_url, notice: 'Negotiator was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negotiator
      @negotiator = Negotiator.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def negotiator_params
      params.require(:negotiator).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def needs_negotiators?
    Negotiator.count > 0
  end
end

app/helpers/journeys_helper.rb
module JourneysHelper

  def maps_loader_script
"https://maps.googleapis.com/maps/api/js?callback=initMap&amp;key=#{ENV['GOOGLE_MAPS_API_KEY']}"

  end
end

app/helpers/negotiators_helper.rb
module NegotiatorsHelper
end

app/views/journeys/_form.html.erb
<%= form_for(@journey,html: { class: "form-inline" }) do |f| %>
<% if @journey.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@journey.errors.count, "error") %> prohibited this journey from being saved:</h2>

  <ul>
    <% @journey.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<span class="span" id="user-form-controls">

    <label  for="journey_negotiator_id" >Negotiator</label>
    <%=f.collection_select  :negotiator_id, Negotiator.all, :id, :username , {}, {class: "form-control"} %>
<label> on
  <%=f.text_field :starts, value: Time.now, class: "form-control" %>
</label>

<span class="padding"> </span>
<div class="actions">
  <%= f.submit 'Create this journey', class: "btn btn-primary" %>
</div>
</span>

<div id="map-data">
<input type='number' id="initial_latitude" value="51.519992">
<input type='number' id="initial_longitude" value="-0.098410">
<input type='number' id="initial_zoom" value="12">
<%=f.text_field :locations %>

</div>

<div class="map-view" id="map">
  <script src="<%= maps_loader_script %>" async defer></script>|
</div>


<% end %>

app/views/journeys/edit.html.erb
<h1>Editing Journey</h1>

<%= render 'form' %>

<%= link_to 'Show', @journey %> |
<%= link_to 'Back', journeys_path %>

app/views/journeys/index.html.erb
<h1>Listing Journeys</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @journeys.each do |journey| %>
    <tr>
      <td><%= journey.negotiator.username %></td>
      <td>on</td>
      <td><%= link_to journey.visits.first.arrival, journey %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/journeys/new.html.erb
<h1>Plan a journey</h1>

<%= render 'form' %>

<p>
  Choose a negotiator, click on the map to place destinations.
</p>
<p>
  When you're done, hit create to build a journey time plan
</p>

app/views/journeys/show.html.erb
<h1>
  Journey made by
  <%= @journey.negotiator.username %> on <%= @journey.visits.first.arrival %>
</h1>

<table class="table">
  <% @journey.visits.each do |v| %>
  <tr> <td><%=v.location.latitude %> , <%= v.location.longitude %> </td><td> arrives </td> <td><%= v.arrival %></td> </tr>
  <% end %>
<table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentyRoute</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Plan a journey", root_url %></li>
          <li><%= link_to "Negotiators", negotiators_url %></li>
          <li><%= link_to "Journeys", journeys_url %></li>
        </ul>
      </nav>
    </div>
  </header>
  <div class="container main-content">
    <div class="jumbotron">
    <p id="notice" ><%= notice %></p>
    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/negotiators/_form.html.erb
<%= form_for(@negotiator) do |f| %>

<% if @negotiator.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@negotiator.errors.count, "error") %> prohibited this negotiator from being saved:</h2>

  <ul>
    <% @negotiator.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<label id:"username">
  Username:
<%= f.text_field :username %>
  <div class="actions">
    <%= f.submit id: 'create_negotiator'  %>
  </div>
</label>
<% end %>

app/views/negotiators/edit.html.erb
<h1>Editing Negotiator</h1>

<%= render 'form' %>

app/views/negotiators/index.html.erb
<h1>Listing Negotiators</h1>

<%= link_to "New", new_negotiator_path, class: "btn btn-default", role:"button" %>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @negotiators.each do |negotiator| %>
    <tr>
      <td><%= link_to negotiator.username, edit_negotiator_path(negotiator) %></td>
      <td><%= link_to 'Delete', negotiator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/negotiators/new.html.erb
<h1>New Negotiator</h1>

<%= render 'form' %>

app/views/negotiators/show.html.erb
<%= link_to 'Edit', edit_negotiator_path(@negotiator) %>